### ISSUE TITLE
Conexão Bluetooth

### ISSUE THREAD

**Issue by tio-ze** [stone-payments/sdk-android#12]
Prezados,

usando o SDK 2.2.10, o pinpad PAX que eu estou usando está apresentando muita intermitência. O stacktrace me diz isso:
java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
06-22 13:51:38.391 29697-29697 W/System.err:     at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
06-22 13:51:38.391 29697-29697/ W/System.err:     at java.util.ArrayList.remove(ArrayList.java:403)
06-22 13:51:38.391 29697-29697/ W/System.err:     at stone.utils.GlobalInformations.removeAllPinpadsFromList(GlobalInformations.java:113)

Alguma sugestão?

**Comment by jgabrielfreitas** [comment]
Boa tarde @tio-ze , você já estava conectado com o pinpad quando ocorreu esse erro?

**Comment by jgabrielfreitas** [comment]
Então tudo certo, esse erro já foi reportado a um tempo atrás, nós vamos subir a correção na próxima build com umas novidades 😄 
A previsão para a próxima build é subir semana que vem

**Comment by tio-ze** [comment]
Vlw @jgabrielfreitas . Vou aguardar.

**Comment by filpgame** [comment]
subimos a versão 2.3.0. Só olhar o changelog :)
