### ISSUE TITLE
Faltando referência da classe R

### ISSUE THREAD

**Issue by programadorthi** [stone-payments/sdk-android#13]
O proguard está alertando que a seguinte classe não existe:

`Warning: stone.providers.TransactionProvider: can't find referenced class com.library.R$raw`
`Warning: stone.providers.TransactionProvider: can't find referenced class com.library.R$raw`
`Warning: stone.providers.TransactionProvider: can't find referenced class com.library.R`

Ao abrir o JAR com o Winrar e acessar o pacote com.library, só existe a classe BuildConfig.

**Comment by filpgame** [comment]
Boa tarde @programadorthi, isso foi em qual versão da SDK?

**Comment by programadorthi** [comment]
@filpgame , a versão que estou usando é a 2.2.11

Já as regras são essas:

`-keep class com.library.** { *; }`
`-keep class stone.** { *; }`

**Comment by programadorthi** [comment]
Olhando o código descompilado da classe TransactionProvider, vocês tem um import para classe:

`import com.library.R.raw;`

Mas em nenhum lugar do JAR de vocês existe essa classe!

Eu não uso a versão _fat do JAR de vocês, pois a dependência do Gson está duplicando outras dependências que tenho.

Mas pelo que vi, a versão _fat também não tem a classe importada no TransactionProvider.

**Comment by filpgame** [comment]
Boa noite @programadorthi 
Já identificamos o ptoblema. 
Logo subiremos uma correção junto com uma série de novidades!

**Comment by programadorthi** [comment]
Vlw @filpgame . Não esqueçam de atualizar o changelog para ficarmos sabendo das novidades.

**Comment by filpgame** [comment]
subimos a versão 2.3.0. Só olhar o changelog :)
