### ISSUE TITLE
Stone code

### ISSUE THREAD

**Issue by tio-ze** [stone-payments/sdk-android#15]
Prezados,

quando troquei meu stone code, recebi a mensagem que o SDK não está ativado. Podem me ajudar?

Abs,

**Comment by filpgame** [comment]
@tio-ze

**Comment by jgabrielfreitas** [comment]
@tio-ze chama o `ActiveApplicationProvider ` passando o Stone Code novo

**Comment by tio-ze** [comment]
Olá @jgabrielfreitas ,

o retorno do ActiveApplicationProvider  é esse aqui:
<?xml version="1.0" encoding="utf-8"?><Document xmlns="urn:TerminalManagementRejectionV02.1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><TermnlMgmtRjctn><Hdr><DwnldTrf>false</DwnldTrf><FrmtVrsn>2.0</FrmtVrsn><CreDtTm>2017-08-22T19:59:20</CreDtTm></Hdr><Rjct><RjctRsn>UNPR</RjctRsn><AddtlInf>A internal server error ocurred getting activation dataset</AddtlInf><MsgInErr/></Rjct></TermnlMgmtRjctn></Document>

Abs,

**Comment by jgabrielfreitas** [comment]
Quem te passou esse StoneCode?
Ele é de Produção ou desenvolvimento?

**Comment by tio-ze** [comment]
Ele é de produção. Ele é um código de migração da Elavon.

**Comment by jgabrielfreitas** [comment]
Pode me passar o Stone Code?

**Comment by tio-ze** [comment]
por aqui?

**Comment by jgabrielfreitas** [comment]
Você usa Telegram, Slack ou Twitter?

**Comment by tio-ze** [comment]
nenhum deles

**Comment by jgabrielfreitas** [comment]
skype?

**Comment by tio-ze** [comment]
sim: marcus-gabriel

**Comment by jgabrielfreitas** [comment]
te procurei aqui, mas não encontrei, me add: jfreitas@buy4.com.br
