### ISSUE TITLE
Endpoints não funcionando

### ISSUE THREAD

**Issue by programadorthi** [stone-payments/sdk-android#17]
Estava realizando uns testes na nossa aplicação e notei que os endpoints além do de produção não estão funcionando.

Requisições ao ambiente de Staging (Environment.STAGING) está retornando 404;

Requisições ao ambiente de homologação (Environment.INTERNAL_HOMOLOG) e sandbox (Environment.SANDBOX) está retornando:
```xml
<Rjct>
  <RjctRsn>UNPR</RjctRsn>
  <AddtlInf>A internal server error ocurred getting activation dataset</AddtlInf>
  <MsgInErr/>
</Rjct>
```

Estou tentando ativar a aplicação usando o ActiveApplicationProvider com o SDK versão 2.4.2

**Comment by jgabrielfreitas** [comment]
@programadorthi sabe se o stonecode que sendo usado é de `STAGING` ou `INTERNAL_HOMOLOG`?

**Comment by programadorthi** [comment]
@jgabrielfreitas aqui sempre usei um único stonecode.

Usávamos antes o `GlobalInformations.developerMode();` e funcionava;

Hoje, com `Environment`, usamos o `Stone.setEnvironment(Environment.SANDBOX)`;

Antes funcionava com o mesmo stonecode. Ontem, começamos a obter a mensagem do comentário anterior.

É necessário um stonecode para cada ambiente?

**Comment by jgabrielfreitas** [comment]
@programadorthi o mesmo stonecode pode ser utilizado em produção ou no ambiente de homologação, mas para isso, ele deve estar dentro do banco relacionado ao ambiente. 
Entre em contato com o time de integrações que eles conseguem fazer isso pra você.
