### ISSUE TITLE
Transações não contabilizadas

### ISSUE THREAD

**Issue by tio-ze** [stone-payments/sdk-android#18]
Prezados,

no dia de ontem (4/9), eu fiz transações que não aparecem no portal. Podem me ajudar?

Abs,

Marcão

**Comment by jgabrielfreitas** [comment]
@tio-ze estive conversando com o Emerson sobre isso e aparentemente vocês passaram essas transações em um ambiente que não é o de produção.

Ela não irá aparecer no portal

Abraço
