### ISSUE TITLE
Teste em HMG

### ISSUE THREAD

**Issue by tio-ze** [stone-payments/sdk-android#20]
Prezados,

no ambiente de HMG, estou usando um cartão desativado e está me retornando essa mensagem. No ambiente de produção é natural a rejeição, afinal o cartão está desativado. Mas eu costumava usar ele em HMG sem problemas. Alguma sugestão?

TransactionObject{idFromBase=4, amount='11398', requestId='null', emailSent='null', timeToPassTransaction='0m 2s', initiatorTransactionKey='20050374608-726500045245634', recipientTransactionIdentification='null', cardHolderNumber='498496*******4533', cardHolderName=' ', date='2017-09-22', time='15:57:02', aid='null', arcq='null', authorizationCode='null', iccRelatedData='null', transactionReference='null', actionCode='null', pinpadUsed='D200-50374608', userModelSale='B012295B0E1E4E47A2900E85CEFBC92A', cne='null', cardBrand=VISA, instalmentTransaction=ONE_INSTALMENT, transactionStatus=REJECTED, instalmentType=None, typeOfTransactionEnum=DEBIT}
09-22 15:57:07.197 16845-20454/ update: 3
09-22 15:57:07.206 16845-20454/ W/System.err: java.lang.Exception: Transaction rejected

**Comment by jgabrielfreitas** [comment]
@tio-ze estou mandando para o time de autorização dar uma olhada no caso

**Comment by tio-ze** [comment]
Oi @jgabrielfreitas . Alguma posição sobre isso?

**Comment by tio-ze** [comment]
Oi @jgabrielfreitas . Alguma posição sobre isso?

**Comment by tio-ze** [comment]
Oi @jgabrielfreitas . Alguma posição sobre isso? Só 26 dias esperando.

**Comment by jgabrielfreitas** [comment]
@tio-ze o que aconteceu com essa transação foi que a chave utilizada pra transacionar em ambiente de produção foi usada em homologação. Por isso a transação foi rejeitada. A mesma nem chegou no autorizador.
