### ISSUE TITLE
Stone.jar download

### ISSUE THREAD

**Issue by balivo** [stone-payments/sdk-android#21]
O arquivo .jar da Stone não está disponível para download.

Como proceder?

**Comment by filpgame** [comment]
Boa tarde @balivo ,
A partir da [v2.4.0](https://github.com/stone-payments/sdk-android/blob/master/changelog.md#v240), a SDK passou a estar disponível via gradle. Siga as instruções de instalação no [readme](https://github.com/stone-payments/sdk-android#instalação)

**Comment by balivo** [comment]
Opa, vlw @filpgame
