### ISSUE TITLE
Retorno da transação caindo no Callback errado

### ISSUE THREAD

**Issue by lucasmacielc** [stone-payments/sdk-android#23]
Boa tarde. 

Atualmente estou utilizando a versão 2.5.0 do SDK, porém algumas vezes a transação é retornada com o status diferente de _APPROVED_ e _PARTIAL_APPROVED_, e mesmo assim acaba caindo no _onSuccess()_ da interface _StoneCallbackInterface_. 

Não consegui entender o motivo desse comportamento pois o código do _TransactionProvider_ é bastante confuso, mas sei que acontece porque peguei algumas vezes esse comportamento.

**Comment by filpgame** [comment]
Olá @lucasmacielc !
Na verdade o evento `onSuccess()` não é pra indicar se a transação foi aprovada ou não, e sim pra indicar quando o fluxo de transação chegou até o final, o `onError()` por sua vez, é pra saber se a transação foi interrompida no meio do fluxo. Ou seja, no `onSuccess()` podem retornar transações aprovadas e negadas.

**Comment by lucasmacielc** [comment]
Olá @filpgame.

Ok, abri a issue baseado na documentação abaixo. 

http://sdkandroid.stone.com.br/docs/provedor-de-transa%C3%A7%C3%A3o-1

![screen shot 2017-12-01 at 11 35 45](https://user-images.githubusercontent.com/14164893/33485028-f8d3bbe0-d68b-11e7-8441-9aff339b9307.png)

Se puderem, atualizem a documentação pois dá a entender outra coisa, talvez outras pessoas tenham tido esse mesmo problema. 

;)

**Comment by filpgame** [comment]
Hm entendi, vamos melhorar essa descrição. 
Obrigado pelo feedback!
