### ISSUE TITLE
Dúvida status de transação.

### ISSUE THREAD

**Issue by rafaelcrz** [stone-payments/sdk-android#24]
Gostaria de saber qual a diferença entre esses dois status. Ambos são negados, porém em qual contexto acontece cada um?

Obrigado

PinpadFeedback.DENIED //"TRANSAC NEGADA"
PinpadFeedback.DENIED_BY_NET //"TRANSAC NEGADA PELA REDE"

**Comment by bragattokk** [comment]
Rafael, 

PinpadFeedback.DENIED //"TRANSAC NEGADA" é um motivo de transação NEGADA após análise do serviço de autorização.

PinpadFeedback.DENIED_BY_NET //"TRANSAC NEGADA PELA REDE" é um motivo de transação NEGADA por alguma falha de conexão.

A principal diferença entre as duas é que a 1ª entra no ciclo de análise (dentro da Stone), enquanto a 2ª nem chega à ser interpretada na Stone.
