### ISSUE TITLE
NullPointerException no TransactionProvider

### ISSUE THREAD

**Issue by lucasmacielc** [stone-payments/sdk-android#25]
Atualmente estamos utilizando a versão 2.5.6 do SDK, porém nessa versão às vezes quando inicio a transação com o Pinpad a conexão entre ele e o device (celular) é perdida, o que acaba gerando um NullPointerException no `TransactionProvider `ao tentar acessar o método `getAcqidx()` pois o `Acquirer` do `PinpadObject` está nulo. 

Isso acontece dentro do construtor do `TransactionProvider`, linha 95. 

Consegue informar se existe alguma maneira de contornar isso? Hoje eu já faço verificações se existe algum Pinpad na lista do SDK de vocês.

**Comment by filpgame** [comment]
Hm, acontece que não colocamos um valor padrão para pinpads que já estavam no nosso banco, resultando esse NPE.
Na próxima versão isso estará corrigido

**Comment by filpgame** [comment]
Corrigido na [v2.5.7](https://github.com/stone-payments/sdk-android/releases/tag/v2.5.7)
Mais uma vez obrigado pelo Feedback! :smile:
