### ISSUE TITLE
Tratamento de erros no cancelamento

### ISSUE THREAD

**Issue by lucasmacielc** [stone-payments/sdk-android#26]
Verifiquei que o `CancellationProvider` não possui um Enum para tratar os problemas com o cancelamento e que hoje só é retornado uma mensagem referente ao problema. 

Poderiam criar status para cada exceção/problema que vier ocorrer com o cancelamento ao invés de só enviar uma mensagem pelo `messageFromAuthorize`? Pois vejam bem, como preciso tratar esses problemas, se por ventura algum dia alguém alterar essa mensagem terei que rever o aplicativo para corrigir a mensagem.

**Comment by filpgame** [comment]
Corrigido na [v2.5.7](https://github.com/stone-payments/sdk-android/releases/tag/v2.5.7)
Obrigado pelo Feedback!
