### ISSUE TITLE
Fatal Exception: android.database.sqlite.SQLiteException 

### ISSUE THREAD

**Issue by lucasmacielc** [stone-payments/sdk-android#28]
Boa tarde,

Estou recebendo esse erro sempre que tento criar um `BluetoothConnectionProvider`. 

Tem alguma solução para esse problema?

![screen shot 2018-04-12 at 13 46 39](https://user-images.githubusercontent.com/14164893/38691696-009b6de4-3e58-11e8-9f3f-783ee2eb2cff.png)

**Comment by filpgame** [comment]
Na versão `v2.5.7` nós fizemos alterações na tabela onde armazenamos infos do Pinpad. Isso acarretou na atualização da versão do banco.
Você fez downgrade da versão da SDK?

**Comment by lucasmacielc** [comment]
Não fiz downgrade. Mantive a versão `v2.5.7`.
