### ISSUE TITLE
Comunicação com POS Bematech

### ISSUE THREAD

**Issue by igorralexsander** [stone-payments/sdk-android#29]
Olá, como funciona o fluxo do SDK com o Pos Go da Bematech e o GPOS 700 da Gertec?

**Comment by ViniciusAugusto** [comment]
Tenho a mesma duvida referente ao PosGo da Bematech, vou acompanhar essa issue.

**Comment by igorralexsander** [comment]
Ja consegui implementar no Pos Go da Bematech Vinicius. Se voce tiver alguma dificuldade posso te ajudar no processo.

**Comment by ViniciusAugusto** [comment]
Opa, quero sim, como tu fez a comunicação com o pinpad integrado do PosGo ? pois na documentação do Stone diz que a conexao é somente via PinPad Bluetooth

**Comment by rrodovalho-stone** [comment]
@igorralexsander Desculpa pela demora, respondendo sua pergunta sobre o funcionamento do fluxo com PosGo e o GPOS700. 

O fluxo do SDK é o mesmo, não existe alteração na integração com a SDK. Lembrando que para suportar esses dois termais suas respectivas dependências devem ser adicionadas no arquivo gradle da aplicação.

**Comment by filpgame** [comment]
@igorralexsander @ViniciusAugusto 
Sobre a documentação, ela estava um pouco atrasada, mas fizemos algumas mudanças para acompanhar as novas features sem afetar as versões anteriores (http://sdkandroid.stone.com.br/v2.6.0), ainda estamos fazendo melhorias mas as principais mudanças já estão lá. De qualquer forma a demo está atualizada e usando todas as features possíveis da SDK com POS Android.
A nova versão ainda não foi amplamente divulgada pois ainda está em fase de testes, mas já pode ser utilizada no ambiente `SANDBOX`, caso encontrem algum bug, mande para [sdkmobile@stone.com.br](mailto:sdkmobile@stone.com.br), assim isso podemos corrigir e acelerar o release da v2.6.0.
