### ISSUE TITLE
Usar sdk em um módulo que não seja o principal

### ISSUE THREAD

**Issue by oliveiradev** [stone-payments/sdk-android#7]
ao tentar criar a seguinte estrutura:

```
|
*app*
|
*secondary-module*
----stone.jar
...
```

O sdk não funciona, temos a seguinte exceção ao tentar acessar as classes , `java.lang.NoClassDefFoundError: stone.qualquer.Classe` , isso ocorre em runtime e não em build time.

**Comment by filpgame** [comment]
Agora a SDK está em um repositório, siga as instruções no [readme.md](https://github.com/stone-payments/sdk-android#instalação)
